name: 🐞 Bug report
description: Report an issue, 中文模板.
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写这个bug报告!
  - type: textarea
    id: bug-description
    attributes:
      label: Bug 描述
      description: 关于bug是什么的清晰而简洁的描述。如果您打算就此问题提交PR，请在描述中告诉我。谢谢!
      placeholder: 我正在做…… 我所期望的是…… 实际发生的是……
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: 系统环境
      render: markdown
      description: |
        示例:
        - **OS**: Ubuntu 20.04
        - **Node**: 18.16.0
        - **packageManager**: pnpm@8.14.0
        - **vite**: 5.0.0
        - **vite-plugin-mock-dev-server**: 1.4.7
      value: |
        - OS:
        - Node:
        - packageManager:
        - vite:
        - vite-plugin-mock-dev-server:
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        请尽量不要插入图像，而是复制粘贴日志文本。
