name: "\U0001F41E Bug report"
description: Report an issue, English Template.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: Environment
      render: markdown
      description: |
        examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 18.16.0
        - **packageManager**: pnpm@8.14.0
        - **vite*: 5.0.0
        - **vite-plugin-mock-dev-server**: 1.4.7
      value: |
        - OS:
        - Node:
        - packageManager:
        - vite:
        - vite-plugin-mock-dev-server:
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please try not to insert an image but copy paste the log text.
